export const PATHS = {
  HOME: "/",
  NEWS: "/news",
  NOTICE: "/notice",
  BOARD: "/board",
  BOARD_FREE: "/board/free",
  BOARD_FREE_WRITE: "/board/free/write",
  BOARD_FREE_POST: "/board/free/:id",
  BOARD_PROMO: "/board/promo",
  BOARD_PROMO_WRITE: "/board/promo/write",
  BOARD_PROMO_POST: "/board/promo/:id",
  ALUMNI: "/alumni",
  GALLERY: "/gallery",
  LOGIN: "/login",
  SIGNUP: "/signup",
  SIGNUP_COMPLETE: "/signup/complete",
  ONBOARDING: "/onboarding",
  ADMIN: "/admin",
  ADMIN_PENDING: "/admin/pending",
  ADMIN_MEMBERS: "/admin/members",
  PENDING_APPROVAL: "/pending-approval",
  REJECTED: "/rejected",
} as const;
