export const PATHS = {
  HOME: "/",
  NEWS: "/news",
  NOTICE: "/notice",
  BOARD: "/board",
  BOARD_FREE: "/board/free",
  BOARD_PROMO: "/board/promo",
  ALUMNI: "/alumni",
  GALLERY: "/gallery",
  LOGIN: "/login",
  SIGNUP: "/signup",
  SIGNUP_COMPLETE: "/signup/complete",
  ONBOARDING: "/onboarding",
  ADMIN: "/admin",
} as const;
